const userTypes = {
    FOLLOW: 'USERS/FOLLOW',
    UNFOLLOW: 'USERS/UNFOLLOW',
    SET_USERS: 'USERS/SET_USERS',
    SET_CURRENTPAGE: 'USERS/SET_CURRENTPAGE',
    SET_TOTALCOUNT: 'USERS/SET_TOTALCOUNT',
    TOGGLE_FETCHING: 'USERS/TOGGLE_FETCHING',
    TOGGLE_BTN_HIDE: 'USERS/TOGGLE_BTN_HIDE'
}

export default userTypes;