const userTypes = {
    FOLLOW: 'FOLLOW',
    UNFOLLOW: 'UNFOLLOW',
    SET_USERS: 'SET_USERS',
    SET_CURRENTPAGE: 'SET_CURRENTPAGE',
    SET_TOTALCOUNT: 'SET_TOTALCOUNT',
    TOGGLE_FETCHING: 'TOGGLE_FETCHING',
    TOGGLE_BTN_HIDE: 'TOGGLE_BTN_HIDE'
}

export default userTypes;