let ProfileTypes = {
    ADD_POST: 'PROFILE/ADD_POST',
    UPDATE_INPUT: 'PROFILE/UPDATE_INPUT',
    SET_PROFILE_USERS: 'PROFILE/SET_PROFILE_USERS',
    SET_PROFILE_STATUS: 'PROFILE/SET_PROFILE_STATUS',
}

export default ProfileTypes;