let ProfileTypes = {
    ADD_POST: 'ADD_POST',
    UPDATE_INPUT: 'UPDATE_INPUT',
    SET_PROFILE_USERS: 'SET_PROFILE_USERS',
    SET_PROFILE_STATUS: 'SET_PROFILE_STATUS',
}

export default ProfileTypes;